AllCops:
  DisplayCopNames: true

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  IgnoredPatterns:
    - !ruby/regexp /^\s*#/

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - config/initializers/**/*

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Style/EmptyMethod:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
